language: scala
scala:
   - 2.11.8

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- rm -r -f $HOME/.ivy2/local/

script:
- sbt ++$TRAVIS_SCALA_VERSION formatAll
- if [[ -n $(git status -s) ]]; then git status && echo 'You need to format your code!' && exit 1; fi
- sbt ++$TRAVIS_SCALA_VERSION clean test || exit 1

jdk:
- oraclejdk8

deploy:
- provider: script
  script: scripts/deploy_bintray.sh
  skip_cleanup: true
  on:
    repo: lustefaniak/explicit-implicits
    tags: true
